dist: xenial
sudo: false

language: node_js
node_js: lts/*
cache: npm

script:
  - npm test
  - npm run test:full-icu

deploy:
  provider: npm
  email: gtx1024+npm@gmail.com
  api_key:
    secure: p24VxYniIsIyy6T6GaooU87mlcuLmVYt7OWSQmBWMhUEVKxV9Sc2aDz4bkl+7bbmsTp9u06cfqT6rlFGG8osp24m6f4DKP9jR6Z1FZjMctufZh2MxPufJpspDkjQUsXwasvTBw4Zzzqc4NSm550yv/ekZW/+1J4J8j81JvXBA2YKghB5QeBar/CAlWentQsmdXBbUknHoRUq2Z+5h5CMHVrbsTdgZNn3tBVNKM1qKsAml33IjbujBygVJXLsCgyY/HnLqWhcYxwP4LGRdOex3rcvoutyh9fatXPJehdFmOc1i1gj7y/3V4AqV2u8QZA4ip9IcS4Bw1tGuyMwlb5BHhEwjjD6KNcPXScZW+zWfUCbuwIn5JUZC+4/6TKa0A7SvJHQR10buIMRCPbixZL/xf2ep/ASLNsU3o/MumTFVUbHTC5wV89Kvy1W576kRIc/GjIFdyqRShKF9jpUsBZx3aEL9F9e6XKYvqTpBGlLtfcXu4LAxi4Dhldo+xa2QQXIZsMkTAYs5lKueIGFwg0ZnFBedKsoP2kJ0C+WtoFdI/BFpbOCjRaAHYRpqbzyW8j+MsdMZvyxuJPd7gxO/6tlGDOjX2CUEQazHX34ZEWXPGxm4pWIfYsJ2jLD7IBxwAcV/wjZzXvc2lmWLrjnjR3P3Vbcs176/pS9xlJc7lHXeEY=
  on:
    tags: true
